# Generated by Django 6.0.4 on 2026-06-10 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diccionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('idioma_origen', models.CharField(max_length=50)),
                ('idioma_destino', models.CharField(default='Español', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praktiko_diccionarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diccionario',
                'verbose_name_plural': 'Diccionarios',
                'ordering': ['nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='EntradaDiccionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_origen', models.CharField(max_length=255)),
                ('texto_destino', models.CharField(max_length=255)),
                ('ejemplo_origen', models.TextField(blank=True)),
                ('ejemplo_destino', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('diccionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='praktiko.diccionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praktiko_entradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de diccionario',
                'verbose_name_plural': 'Entradas de diccionario',
                'ordering': ['texto_origen'],
            },
        ),
        migrations.CreateModel(
            name='SesionPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tarjetas', models.PositiveIntegerField(default=0)),
                ('aciertos', models.PositiveIntegerField(default=0)),
                ('fallos', models.PositiveIntegerField(default=0)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('diccionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_practica', to='praktiko.diccionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praktiko_sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de práctica',
                'verbose_name_plural': 'Sesiones de práctica',
                'ordering': ['-iniciada_en'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_elegida', models.CharField(max_length=255)),
                ('respuesta_correcta', models.CharField(max_length=255)),
                ('correcta', models.BooleanField(default=False)),
                ('respondida_en', models.DateTimeField(auto_now_add=True)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_practica', to='praktiko.entradadiccionario')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='praktiko.sesionpractica')),
            ],
            options={
                'verbose_name': 'Respuesta de práctica',
                'verbose_name_plural': 'Respuestas de práctica',
                'ordering': ['respondida_en'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('diccionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='praktiko.diccionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praktiko_temas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['nombre'],
                'unique_together': {('usuario', 'diccionario', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='sesionpractica',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_practica', to='praktiko.tema'),
        ),
        migrations.AddField(
            model_name='entradadiccionario',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='praktiko.tema'),
        ),
    ]
