# Generated by Django 6.0.4 on 2026-06-10 18:50

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktiko', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadiccionario',
            name='nivel',
            field=models.CharField(choices=[('inicial', 'Inicial'), ('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='inicial', max_length=20),
        ),
        migrations.AddField(
            model_name='entradadiccionario',
            name='proxima_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entradadiccionario',
            name='ultima_practica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entradadiccionario',
            name='veces_acertada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entradadiccionario',
            name='veces_fallada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entradadiccionario',
            name='veces_practicada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respuestapractica',
            name='texto_origen',
            field=models.CharField(default='Sin dato', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesionpractica',
            name='modo',
            field=models.CharField(choices=[('tema', 'Por tema'), ('dificiles', 'Palabras difíciles'), ('falladas', 'Palabras falladas'), ('aleatorio', 'Aleatorio')], default='tema', max_length=20),
        ),
        migrations.AddField(
            model_name='tema',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='entradadiccionario',
            index=models.Index(fields=['usuario', 'diccionario'], name='praktiko_en_usuario_6c32b0_idx'),
        ),
        migrations.AddIndex(
            model_name='entradadiccionario',
            index=models.Index(fields=['usuario', 'tema'], name='praktiko_en_usuario_931390_idx'),
        ),
        migrations.AddIndex(
            model_name='entradadiccionario',
            index=models.Index(fields=['usuario', 'nivel'], name='praktiko_en_usuario_2b5040_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestapractica',
            index=models.Index(fields=['correcta'], name='praktiko_re_correct_78fa21_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestapractica',
            index=models.Index(fields=['respondida_en'], name='praktiko_re_respond_c431ef_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionpractica',
            index=models.Index(fields=['usuario', 'diccionario'], name='praktiko_se_usuario_9a2d78_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionpractica',
            index=models.Index(fields=['usuario', 'iniciada_en'], name='praktiko_se_usuario_4eaf74_idx'),
        ),
    ]
