# Generated by Django 6.0.4 on 2026-06-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktiko', '0002_entradadiccionario_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diccionario',
            name='color',
            field=models.CharField(blank=True, default='#2563eb', help_text='Color principal del diccionario en formato hexadecimal.', max_length=20),
        ),
        migrations.AddField(
            model_name='diccionario',
            name='icono',
            field=models.CharField(blank=True, default='📚', help_text='Emoji o icono visual del diccionario. Ejemplo: 🇷🇺, 🇬🇧, 📚', max_length=10),
        ),
    ]
