# Generated by Django 6.0.4 on 2026-06-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktiko', '0003_diccionario_color_diccionario_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='color',
            field=models.CharField(blank=True, default='#64748b', max_length=20),
        ),
        migrations.AddField(
            model_name='tema',
            name='icono',
            field=models.CharField(blank=True, default='📁', max_length=10),
        ),
        migrations.AddField(
            model_name='tema',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
