# Generated by Django 6.0.4 on 2026-06-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktiko', '0004_tema_color_tema_icono_tema_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadiccionario',
            name='tipo',
            field=models.CharField(choices=[('palabra', 'Palabra'), ('frase', 'Frase')], default='palabra', max_length=20),
        ),
    ]
