# Generated by Django 6.0.4 on 2026-06-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktiko', '0005_entradadiccionario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestapractica',
            name='evaluacion',
            field=models.CharField(choices=[('error', 'Error'), ('dificil', 'Difícil'), ('correcto', 'Correcto'), ('facil', 'Fácil')], default='correcto', max_length=20),
        ),
    ]
