# Generated by Django 6.0.4 on 2026-06-17 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktiko', '0006_respuestapractica_evaluacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praktiko_grupos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de aprendizaje',
                'verbose_name_plural': 'Grupos de aprendizaje',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InvitacionGrupoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('respondida_en', models.DateTimeField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='praktiko.grupoaprendizaje')),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praktiko_invitaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('invitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praktiko_invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitación a grupo',
                'verbose_name_plural': 'Invitaciones a grupos',
            },
        ),
        migrations.CreateModel(
            name='MiembroGrupoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('miembro', 'Miembro')], default='miembro', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('unido_en', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='praktiko.grupoaprendizaje')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praktiko_grupos_miembro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de grupo',
                'verbose_name_plural': 'Miembros de grupo',
                'unique_together': {('grupo', 'usuario')},
            },
        ),
    ]
