# Generated by Django 6.0.4 on 2026-06-17 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktiko', '0007_grupoaprendizaje_invitaciongrupoaprendizaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diccionario',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diccionarios', to='praktiko.grupoaprendizaje'),
        ),
    ]
