# Generated by Django 6.0.4 on 2026-06-19 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktiko', '0008_diccionario_grupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitaciongrupoaprendizaje',
            options={},
        ),
        migrations.CreateModel(
            name='EstadisticaEntradaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veces_preguntada', models.PositiveIntegerField(default=0)),
                ('aciertos', models.PositiveIntegerField(default=0)),
                ('fallos', models.PositiveIntegerField(default=0)),
                ('ultimo_acierto', models.DateTimeField(blank=True, null=True)),
                ('ultimo_fallo', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_usuario', to='praktiko.entradadiccionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praktiko_estadisticas_entradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
