# Generated by Django 6.0.4 on 2026-06-19 20:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praktiko', '0009_alter_invitaciongrupoaprendizaje_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadisticaentradausuario',
            options={'ordering': ['-fallos', '-veces_preguntada'], 'verbose_name': 'Estadística de entrada por usuario', 'verbose_name_plural': 'Estadísticas de entradas por usuario'},
        ),
        migrations.AlterModelOptions(
            name='invitaciongrupoaprendizaje',
            options={'verbose_name': 'Invitación a grupo', 'verbose_name_plural': 'Invitaciones a grupos'},
        ),
        migrations.AlterUniqueTogether(
            name='estadisticaentradausuario',
            unique_together={('usuario', 'entrada')},
        ),
    ]
