# Generated by Django 6.0.4 on 2026-07-16 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktiko', '0010_alter_estadisticaentradausuario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('oficial', 'Oficial'), ('nivel', 'Nivel'), ('grupo', 'Grupo'), ('ia', 'IA')], default='normal', max_length=20)),
                ('sentido', models.CharField(choices=[('origen_destino', 'Origen → destino'), ('destino_origen', 'Destino → origen'), ('mixto', 'Mixto')], default='mixto', max_length=30)),
                ('numero_preguntas', models.PositiveIntegerField(default=15)),
                ('aciertos', models.PositiveIntegerField(default=0)),
                ('fallos', models.PositiveIntegerField(default=0)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nota', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('tiempo_segundos', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='en_curso', max_length=20)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('diccionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='praktiko.diccionario')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes', to='praktiko.tema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praktiko_examenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['-iniciada_en'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentido', models.CharField(choices=[('origen_destino', 'Origen → destino'), ('destino_origen', 'Destino → origen'), ('mixto', 'Mixto')], max_length=30)),
                ('texto_pregunta', models.CharField(max_length=255)),
                ('respuesta_usuario', models.CharField(blank=True, max_length=255)),
                ('respuesta_correcta', models.CharField(max_length=255)),
                ('correcta', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField()),
                ('respondida_en', models.DateTimeField(auto_now_add=True)),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_examen', to='praktiko.entradadiccionario')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='praktiko.examen')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_examen', to='praktiko.tema')),
            ],
            options={
                'verbose_name': 'Respuesta de examen',
                'verbose_name_plural': 'Respuestas de examen',
                'ordering': ['orden'],
            },
        ),
        migrations.AddIndex(
            model_name='examen',
            index=models.Index(fields=['usuario', 'iniciada_en'], name='praktiko_ex_usuario_467980_idx'),
        ),
        migrations.AddIndex(
            model_name='examen',
            index=models.Index(fields=['usuario', 'estado'], name='praktiko_ex_usuario_dec12a_idx'),
        ),
        migrations.AddIndex(
            model_name='examen',
            index=models.Index(fields=['diccionario', 'tema'], name='praktiko_ex_diccion_4f5ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestaexamen',
            index=models.Index(fields=['examen', 'correcta'], name='praktiko_re_examen__07322f_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestaexamen',
            index=models.Index(fields=['tema'], name='praktiko_re_tema_id_ee116a_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestaexamen',
            index=models.Index(fields=['respondida_en'], name='praktiko_re_respond_9d8d6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='respuestaexamen',
            unique_together={('examen', 'orden')},
        ),
    ]
