# Generated by Django 6.0.4 on 2026-10-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktiko', '0012_sesion_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiondemo',
            name='solicitudes_ia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
