# Generated by Django 6.0.4 on 2026-10-09 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktiko', '0013_sesiondemo_solicitudes_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAltaDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_hash', models.CharField(max_length=64, unique=True)),
                ('ventana_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('altas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Control de altas de demostración',
                'verbose_name_plural': 'Controles de altas de demostración',
            },
        ),
    ]
