# Generated by Django 6.0.4 on 2026-05-19 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbitoTarea',
            fields=[
                ('id_ambito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gestor_tareas_tbambitos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#6c757d', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gestor_tareas_tbestados',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gestor_tareas_tbgrupos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RolGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gestor_tareas_tbroles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gestor_tareas_tbtecnicos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visible', models.CharField(blank=True, max_length=150, null=True)),
                ('puesto', models.CharField(blank=True, max_length=150, null=True)),
                ('departamento', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto_url', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_taskpilot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gestor_tareas_tbperfiles_usuario',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_tarea', models.IntegerField()),
                ('fecha', models.DateField()),
                ('prioridad', models.CharField(default='Normal', max_length=20)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuario_creador', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_objetivo', models.DateTimeField(blank=True, null=True)),
                ('ambito', models.ForeignKey(blank=True, db_column='id_ambito', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='gestor_tareas.ambitotarea')),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='gestor_tareas.estadotarea')),
                ('grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='gestor_tareas.grupotrabajo')),
                ('tecnico', models.ForeignKey(blank=True, db_column='id_tecnico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='gestor_tareas.tecnico')),
            ],
            options={
                'db_table': 'gestor_tareas_tbtareas',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id_subtarea', models.BigAutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=500)),
                ('completada', models.BooleanField(default=False)),
                ('creada_por_ia', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(db_column='id_tarea', on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='gestor_tareas.tarea')),
            ],
            options={
                'db_table': 'gestor_tareas_tbsubtareas',
                'ordering': ['completada', 'id_subtarea'],
            },
        ),
        migrations.CreateModel(
            name='NotaTarea',
            fields=[
                ('id_nota', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('texto', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('tarea', models.ForeignKey(db_column='id_tarea', on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestor_tareas.tarea')),
            ],
            options={
                'db_table': 'gestor_tareas_tbnotas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TecnicoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='gestor_tareas.grupotrabajo')),
                ('tecnico', models.ForeignKey(db_column='id_tecnico', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='gestor_tareas.tecnico')),
            ],
            options={
                'db_table': 'gestor_tareas_tbtecnicos_grupos',
                'ordering': ['grupo__nombre', 'tecnico__nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_admin_gestor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_gestor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gestor_tareas_tbusuarios',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='gestor_tareas.grupotrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_gestor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gestor_tareas_tbusuarios_grupos',
                'ordering': ['grupo__nombre', 'usuario__username'],
                'unique_together': {('usuario', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioRolGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='gestor_tareas.rolgestor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_gestor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gestor_tareas_tbusuarios_roles',
                'ordering': ['usuario__username', 'rol__nombre'],
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
