# Generated by Django 6.0.4 on 2026-04-16 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de trabajo',
                'verbose_name_plural': 'Grupos de trabajo',
                'db_table': 'gestor_tareas_tbgrupos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RolGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol del gestor',
                'verbose_name_plural': 'Roles del gestor',
                'db_table': 'gestor_tareas_tbroles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_admin_gestor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_gestor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario del gestor',
                'verbose_name_plural': 'Usuarios del gestor',
                'db_table': 'gestor_tareas_tbusuarios',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='gestor_tareas.grupotrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_gestor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relación usuario-grupo',
                'verbose_name_plural': 'Relaciones usuario-grupo',
                'db_table': 'gestor_tareas_tbusuarios_grupos',
                'ordering': ['grupo__nombre', 'usuario__username'],
                'unique_together': {('usuario', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioRolGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='gestor_tareas.rolgestor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_gestor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relación usuario-rol',
                'verbose_name_plural': 'Relaciones usuario-rol',
                'db_table': 'gestor_tareas_tbusuarios_roles',
                'ordering': ['usuario__username', 'rol__nombre'],
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
