# Generated by Django 6.0.4 on 2026-05-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupotrabajo',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='rolgestor',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='usuariogestor',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterModelOptions(
            name='usuariogrupo',
            options={'ordering': ['grupo__nombre', 'usuario__username']},
        ),
        migrations.AlterModelOptions(
            name='usuariorolgestor',
            options={'ordering': ['usuario__username', 'rol__nombre']},
        ),
    ]
