# Generated by Django 6.0.4 on 2026-05-19 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadotarea',
            options={'ordering': ['grupo__nombre', 'orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='estadotarea',
            name='grupo',
            field=models.ForeignKey(db_column='id_grupo', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='gestor_tareas.grupotrabajo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estadotarea',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='estadotarea',
            unique_together={('grupo', 'nombre')},
        ),
    ]
