# Generated by Django 6.0.4 on 2026-05-16 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0002_alter_grupotrabajo_options_alter_rolgestor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gestor_tareas_tbtecnicos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AmbitoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambitos', to='gestor_tareas.grupotrabajo')),
            ],
            options={
                'db_table': 'gestor_tareas_tbambitos',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color_clase', models.CharField(default='azul', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='gestor_tareas.grupotrabajo')),
            ],
            options={
                'db_table': 'gestor_tareas_tbestados',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('nombre', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='TecnicoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='gestor_tareas.grupotrabajo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='gestor_tareas.tecnico')),
            ],
            options={
                'db_table': 'gestor_tareas_tbtecnicos_grupos',
                'ordering': ['grupo__nombre', 'tecnico__nombre'],
                'unique_together': {('tecnico', 'grupo')},
            },
        ),
    ]
