# Generated by Django 6.0.4 on 2026-05-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0002_alter_estadotarea_options_estadotarea_grupo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tecnicogrupo',
            unique_together={('tecnico', 'grupo')},
        ),
    ]
