# Generated by Django 6.0.4 on 2026-05-16 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0003_tecnico_ambitotarea_estadotarea_tecnicogrupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarea', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_objetivo', models.DateTimeField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Normal', 'Normal'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Normal', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuario_creador', models.CharField(blank=True, max_length=150, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('ambito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='gestor_tareas.ambitotarea')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='gestor_tareas.estadotarea')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='gestor_tareas.grupotrabajo')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='gestor_tareas.tecnico')),
            ],
            options={
                'db_table': 'gestor_tareas_tbtareas',
                'ordering': ['-fecha_creacion', '-id'],
                'unique_together': {('grupo', 'numero_tarea')},
            },
        ),
    ]
