# Generated by Django 6.0.4 on 2026-05-16 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0004_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambitotarea',
            name='grupo',
            field=models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='ambitos', to='gestor_tareas.grupotrabajo'),
        ),
        migrations.AlterField(
            model_name='estadotarea',
            name='grupo',
            field=models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='gestor_tareas.grupotrabajo'),
        ),
        migrations.AlterField(
            model_name='tecnicogrupo',
            name='grupo',
            field=models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='gestor_tareas.grupotrabajo'),
        ),
        migrations.AlterField(
            model_name='tecnicogrupo',
            name='tecnico',
            field=models.ForeignKey(db_column='id_tecnico', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='gestor_tareas.tecnico'),
        ),
    ]
