# Generated by Django 6.0.4 on 2026-05-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0005_alter_ambitotarea_grupo_alter_estadotarea_grupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupotrabajo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='id',
        ),
        migrations.AddField(
            model_name='grupotrabajo',
            name='id_grupo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='id_tecnico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
