# Generated by Django 6.0.4 on 2026-05-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0006_remove_grupotrabajo_id_remove_tecnico_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupotrabajo',
            name='id_grupo',
        ),
        migrations.AddField(
            model_name='grupotrabajo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
