# Generated by Django 6.0.4 on 2026-05-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0007_remove_grupotrabajo_id_grupo_grupotrabajo_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ambitotarea',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='estadotarea',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tecnicogrupo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ambitotarea',
            name='id_ambito',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='estadotarea',
            name='id_estado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ambitotarea',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='estadotarea',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.RemoveField(
            model_name='ambitotarea',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='ambitotarea',
            name='id',
        ),
        migrations.RemoveField(
            model_name='estadotarea',
            name='color_clase',
        ),
        migrations.RemoveField(
            model_name='estadotarea',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='estadotarea',
            name='id',
        ),
    ]
