# Generated by Django 6.0.4 on 2026-05-16 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0008_alter_ambitotarea_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tarea',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuario_asignado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='ambito',
            field=models.ForeignKey(db_column='id_ambito', on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='gestor_tareas.ambitotarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='gestor_tareas.estadotarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='grupo',
            field=models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='gestor_tareas.grupotrabajo'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='numero_tarea',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tecnico',
            field=models.ForeignKey(blank=True, db_column='id_tecnico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='gestor_tareas.tecnico'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='usuario_creador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='NotaTarea',
            fields=[
                ('id_nota', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('texto', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('tarea', models.ForeignKey(db_column='id_tarea', on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestor_tareas.tarea')),
            ],
            options={
                'db_table': 'gestor_tareas_tbnotas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_completada',
        ),
    ]
