# Generated by Django 6.0.4 on 2026-05-16 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0009_alter_tarea_unique_together_tarea_usuario_asignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='ambito',
            field=models.ForeignKey(blank=True, db_column='id_ambito', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='gestor_tareas.ambitotarea'),
        ),
    ]
