# Generated by Django 6.0.4 on 2026-05-17 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0010_alter_tarea_ambito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id_subtarea', models.BigAutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=500)),
                ('completada', models.BooleanField(default=False)),
                ('creada_por_ia', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(db_column='id_tarea', on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='gestor_tareas.tarea')),
            ],
            options={
                'db_table': 'gestor_tareas_tbsubtareas',
                'ordering': ['completada', 'id_subtarea'],
            },
        ),
    ]
