# Generated by Django 6.0.4 on 2026-05-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0012_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadotarea',
            name='color',
            field=models.CharField(default='#6c757d', max_length=20),
        ),
    ]
