# Generated by Django 6.0.4 on 2026-09-14 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.CharField(blank=True, help_text='Ruta de la imagen dentro de static/dcs/. Ejemplo: imagenes/F4EPhantom.png', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Aeronave',
                'verbose_name_plural': 'Aeronaves',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContenidoDCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('tipo', models.CharField(choices=[('curso', 'Curso'), ('campana', 'Campaña'), ('misiones', 'Misiones')], default='misiones', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('situacion', models.TextField(blank=True)),
                ('objetivo', models.TextField(blank=True)),
                ('imagen', models.CharField(blank=True, help_text='Ruta de la imagen dentro de static/dcs/. Ejemplo: imagenes/fuegoenelestrecho.png', max_length=255)),
                ('estado', models.CharField(choices=[('publicado', 'Publicado'), ('desarrollo', 'En desarrollo'), ('oculto', 'Oculto')], default='publicado', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='dcs.aeronave')),
            ],
            options={
                'verbose_name': 'Contenido DCS',
                'verbose_name_plural': 'Contenidos DCS',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='MisionDCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('url_descarga', models.URLField(blank=True, max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misiones', to='dcs.contenidodcs')),
            ],
            options={
                'verbose_name': 'Misión DCS',
                'verbose_name_plural': 'Misiones DCS',
                'ordering': ['orden', 'numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='contenidodcs',
            constraint=models.UniqueConstraint(fields=('aeronave', 'slug'), name='dcs_contenido_aeronave_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='misiondcs',
            constraint=models.UniqueConstraint(fields=('contenido', 'numero'), name='dcs_mision_contenido_numero_unique'),
        ),
    ]
