# Generated by Django 6.0.4 on 2026-09-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='imagen_subida',
            field=models.ImageField(blank=True, null=True, upload_to='dcs/aeronaves/', verbose_name='Imagen subida'),
        ),
        migrations.AddField(
            model_name='contenidodcs',
            name='imagen_subida',
            field=models.ImageField(blank=True, null=True, upload_to='dcs/contenidos/', verbose_name='Imagen subida'),
        ),
    ]
