# Generated by Django 6.0.4 on 2026-09-15 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs', '0002_aeronave_imagen_subida_contenidodcs_imagen_subida'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionMisionDCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la versión')),
                ('url_descarga', models.URLField(max_length=500, verbose_name='URL de descarga')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='dcs.misiondcs')),
            ],
            options={
                'verbose_name': 'Versión de misión DCS',
                'verbose_name_plural': 'Versiones de misiones DCS',
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('mision', 'nombre'), name='dcs_version_mision_nombre_unique')],
            },
        ),
    ]
