# Generated by Django 6.0.4 on 2026-10-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('descripcion_corta', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='portfolio/proyectos/')),
                ('tecnologias', models.CharField(blank=True, max_length=300)),
                ('url_proyecto', models.URLField(blank=True)),
                ('url_github', models.URLField(blank=True)),
                ('estado', models.CharField(choices=[('desarrollo', 'En desarrollo'), ('finalizado', 'Finalizado'), ('mantenimiento', 'En mantenimiento')], default='desarrollo', max_length=20)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
    ]
